import { NextUIClientProvider } from "@/components/providers/nextui-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/providers/toast-provider";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/providers/session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Postify",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" className="dark">
      <body className={inter.className} suppressHydrationWarning>
        <SessionProvider session={session}>
          <NextUIClientProvider>
            <Toaster />
            {children}
          </NextUIClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
