import { NextUIClientProvider } from "@/components/providers/nextui-provider"

import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { getServerSession } from "next-auth"

import SessionProvider from "@/components/providers/session-provider"
import { Toaster } from "@/components/providers/toast-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Postify",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang="en" className="dark" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <NextUIClientProvider>
            <Toaster />
            {children}
          </NextUIClientProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
